version: 0.2

env:
  variables:
    RUN_MIGRATIONS: "true"
    RUN_SEED: "false"

phases:
  pre_build:
    commands:
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$(echo "$IMAGE_URI" | cut -d/ -f1)"
  build:
    commands:
      - echo "Pulling image $IMAGE_URI"
      - docker pull "$IMAGE_URI"
      - if [ "$RUN_MIGRATIONS" = "true" ]; then docker run --rm -e DATABASE_URL="$DATABASE_URL" "$IMAGE_URI" bun /usr/src/app/backend/src/db/migrate.ts; fi
      - if [ "$RUN_SEED" = "true" ]; then docker run --rm -e DATABASE_URL="$DATABASE_URL" "$IMAGE_URI" bun /usr/src/app/scripts/seed-organizations.ts; fi
