#!/usr/bin/env bun
/**
 * Setup script to create .env files for local development
 * Run with: bun scripts/setup-env.ts
 */

import { existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const BACKEND_ENV_CONTENT = `# Daadaar Backend - Local Development Environment
# Generated by setup-env.ts

# =============================================================================
# DATABASE (Docker PostgreSQL)
# =============================================================================
DATABASE_URL=postgresql://daadaar:daadaar_dev_password@localhost:5432/daadaar

# =============================================================================
# API SERVER
# =============================================================================
PORT=4000
NODE_ENV=development

# =============================================================================
# CORS / FRONTEND
# =============================================================================
FRONTEND_URL=http://localhost:3000
APP_URL=http://localhost:3000

# =============================================================================
# REDIS (Sessions and Rate Limiting)
# =============================================================================
REDIS_URL=redis://localhost:6379

# =============================================================================
# AUTHENTICATION (Development values - change in production!)
# =============================================================================
JWT_SECRET=dev-jwt-secret-change-in-production-use-strong-random-value
JWT_EXPIRES_IN=30d
SESSION_SECRET=dev-session-secret-change-in-production
ENCRYPTION_KEY=dev-encryption-key-32chars!!

# =============================================================================
# AWS S3 (Optional for local dev)
# =============================================================================
# AWS_ACCESS_KEY_ID=
# AWS_SECRET_ACCESS_KEY=
# AWS_REGION=us-east-1
# AWS_S3_BUCKET=daadaar-media

# =============================================================================
# OAUTH (Optional for local dev)
# =============================================================================
# GOOGLE_CLIENT_ID=
# GOOGLE_CLIENT_SECRET=
# GITHUB_CLIENT_ID=
# GITHUB_CLIENT_SECRET=

# =============================================================================
# AI (Optional for local dev)
# =============================================================================
# OPENAI_API_KEY=

# =============================================================================
# MONITORING (Optional for local dev)
# =============================================================================
# SENTRY_DSN=
# POSTHOG_KEY=
# POSTHOG_HOST=https://app.posthog.com
`;

const DATABASE_ENV_CONTENT = `# Daadaar Database - Local Development Environment
# Generated by setup-env.ts

DATABASE_URL=postgresql://daadaar:daadaar_dev_password@localhost:5432/daadaar
`;

const projectRoot = join(import.meta.dir, '..');

function createEnvFile(relativePath: string, content: string) {
  const fullPath = join(projectRoot, relativePath);

  if (existsSync(fullPath)) {
    console.log(`⚠️  ${relativePath} already exists, skipping...`);
    return false;
  }

  writeFileSync(fullPath, content);
  console.log(`✅ Created ${relativePath}`);
  return true;
}

console.log('🔧 Setting up environment files for local development...\n');

createEnvFile('backend/.env', BACKEND_ENV_CONTENT);
createEnvFile('database/.env', DATABASE_ENV_CONTENT);

console.log(`
📋 Next steps:
   1. Start PostgreSQL: bun run docker:up
   2. Wait for DB to be ready (check with: docker compose logs postgres)
   3. Run migrations: bun run db:push
   4. Start development: bun run dev

🔒 Note: .env files contain secrets and are gitignored.
         Never commit them to version control!
`);
